[package]
name = "wisp"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
hex = "0.4.3"
rayon = "1.10.0"
ring = "0.17.8"
serde = { version = "1.0.210", features = ["derive"] }
serde_bytes = "0.11.15"
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["full"] }
