[package]
name = "wisp-wallet"
description = "A command-line interface wallet for managing Wisp coins and interacting with the network."
include = ["src/**/*", "README.md"]
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0.100"
wisp-core = { path = "../wisp-core" }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.48.0", features = ["full"] }
serde_json = "1.0.145"
argon2 = "0.5.3"
ecdsa = { version = "0.16.9", features = [
    "signing",
    "verifying",
    "serde",
    "pem",
] }
k256 = { version = "0.13.4", features = ["serde", "pem"] }
inquire = "0.9.1"
clap = { version = "4.5.51", features = ["derive"] }
termion = "4.0.5"
log = "0.4.28"
env_logger = "0.11.8"
base64 = "0.22.1"
hex = "0.4.3"
toml = "0.9.8"
chrono = { version = "0.4.42", features = ["serde"] }
rand = "0.9"
aes-gcm = "0.10.3"
bip39 = "2.2.2"
