[package]
name = "wisp-core"
description = "Core data structures, cryptography, and networking primitives for the Wisp blockchain."
include = ["src/**/*", "README.md"]
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
aes-gcm = "0.10.3"
anyhow = "1.0.100"
bigdecimal = "0.4.9"
bincode = { version = "2.0.1", features = ["serde"] }
bip32 = "0.5.3"
bip39 = "2.2.0"
chrono = { version = "0.4.42", features = ["serde"] }
ecdsa = { version = "0.16.9", features = [
    "signing",
    "verifying",
    "serde",
    "pem",
] }
flume = "0.11.1"
hex = "0.4.3"
k256 = { version = "0.13.4", features = ["serde", "pem"] }
log = "0.4.28"
num_cpus = "1.17.0"
pem = "3.0.6"
rand = "0.9"
rayon = "1.11.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_bytes = "0.11.19"
serde_with = { version = "3.15.1", features = ["chrono", "hex"] }
sha2 = "0.10.9"
sled = "0.34.7"
tempfile = "3.23.0"
tokio = { version = "1.48.0", features = ["full"] }
toml = "0.9.8"
uint = "0.10.0"
uuid = { version = "1.18.1", features = ["v4", "serde"] }
zeroize = "1.8.2"
